### ISSUE TITLE
Could Elle tell the difference between snapshot isolation and strong-session-snapshot-isolation?

### ISSUE THREAD

**Issue by Tsunaou** [jepsen-io/elle#17]
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/23613366/203554570-f3d2769f-fb82-4303-ad87-5d02dea41cd6.png">
In the consistency models you provided in README, I found that you have distinguished PL-SI (snapshot-isolation), strong-session-snapshot-isolation and strong-snapshot-isolation. However, it seems that you have not implemented this in Elle?

![image](https://user-images.githubusercontent.com/23613366/203555979-11113d60-ff99-4300-8ff9-d7098b34d84e.png)
I  constructed this history of 4 transactions running in 3 processes. There is a cycle as shown in the picture above. In other words, strong-session-snapshot-isolation is violated by this history.

```clojure
(def h [{:type :invoke, :value [[:r :x nil] [:r :z nil]], :process 0, :index 0}
        {:type :ok, :value [[:r :x nil] [:r :z [1]]], :process 0, :index 1}
        {:type :invoke, :value [[:append :x 1]], :process 1, :index 2}
        {:type :ok, :value [[:append :x 1]], :process 1, :index 3}
        {:type :invoke, :value [[:r :z nil]], :process 1, :index 4}
        {:type :ok, :value [[:r :z nil]], :process 1, :index 5}
        {:type :invoke, :value [[:append :z 1]], :process 2, :index 6}
        {:type :ok, :value [[:append :z 1]], :process 2, :index 7}])
```

However, when I cloned the latest release v0.1.5, and checked this history by Elle, the result is valid. 

![image](https://user-images.githubusercontent.com/23613366/203556969-cf67df3e-61d5-4ccd-8d48-27b7bc46f7be.png)

Did I miss any key steps or did not set any key parameters when checking?

I would appreciate it if you could give a prompt reply.

Sincerely,
Young

**Comment by aphyr** [comment]
Aha! An email from Alexey Gotsman got me looking at the right part of the code by accident--I wasn't certain, when I implemented g-nonadjacent, whether it could be properly generalized to realtime and process variants. Your example is *not* g-single-process, but g-nonadjacent-process, and because of my earlier caution I didn't implement that particular checker. After a few years of experience with nonadjacent, and your issue, I think it's probably reasonable for us to consider this a strong session SI violation. I've added support for it to elle, and the test now passes. :-)

**Comment by Tsunaou** [comment]
Thanks!

**Comment by aphyr** [comment]
<sigh> If I had known you were planning to write a paper based on this issue which claimed to invalidate the core claim of our work, I would have spent more time on my response. "Efficient but not sound" is obviously a typo: that should be "Efficient but not complete". I am also baffled at how "strong-session-SI is implemented, and it does work" became "we have confirmed with the developer that Elle does not [check strong session SI]". 

Like... that's the exact opposite of what I said. What the fuck.

**Comment by aphyr** [comment]
> we simply quoted what you said in the comment

Had you quoted the comment, it would have been obvious that this was not a soundness property.

> What we were not aware of was that Elle was not sound for efficiency. 

Again, this is not true. Our paper discussed soundness and completeness in depth. "[T]here are in general anomalies it cannot detect" is obviously referring to completeness. <sigh>

In general: I get so, so many support requests. I try my best to respond, but I'm not paid for any of this work--I'm often squeezing responses to GH issues in between sets at the gym or during breakfast. I'm not always gonna get that right. If you're gonna publish a paper refuting the central claim of a work, and think a sentence seems completely bonkers, *double-check* first.

**Comment by siliunobi** [comment]
We have clarified the above discussed issues; see the [updated version](https://arxiv.org/pdf/2301.07313v2.pdf).
