### ISSUE TITLE
list-append/sorted-values might be broken with history object

### ISSUE THREAD

**Issue by juangugit** [jepsen-io/elle#22]
I am running a Jepsen test from Jepsen-io/mongodb and using [jepsen "0.3.3-SNAPSHOT"], I am seeing this error below. Can anyone help? Thanks
here is the lein run command
`lein run test-all -w list-append -n n1 -n n2 -n n3 -n n4 -n n5 -n n6 -n n7 -n n8 -n n9 -r 1000 --concurrency 3n --time-limit 240 --max-writes-per-key 128 --read-concern majority --write-concern majority --txn-read-concern snapshot --txn-write-concern majority --nemesis-interval 1 --nemesis partition --test-count 1`

here is the error message:
> 
> [2023/08/24 00:06:52.509] INFO [2023-08-24 00:06:52,428] jepsen test runner - jepsen.core Analyzing...
> [2023/08/24 00:06:52.509] WARN [2023-08-24 00:06:52,508] clojure-agent-send-off-pool-78 - jepsen.checker Error while checking history:
> [2023/08/24 00:06:52.509] java.lang.ClassCastException: class clojure.lang.LazySeq cannot be cast to class jepsen.history.IHistory (clojure.lang.LazySeq and jepsen.history.IHistory are in unnamed module of loader 'app')
> [2023/08/24 00:06:52.509] 	at elle.list_append$sorted_values.invokeStatic(list_append.clj:257)
> [2023/08/24 00:06:52.509] 	at elle.list_append$sorted_values.invoke(list_append.clj:223)
> [2023/08/24 00:06:52.509] 	at jepsen.mongodb.list_append$divergence_stats_checker$reify__2906.check(list_append.clj:174)
> [2023/08/24 00:06:52.509] 	at jepsen.checker$check_safe.invokeStatic(checker.clj:86)
> [2023/08/24 00:06:52.509] 	at jepsen.checker$check_safe.invoke(checker.clj:79)
> [2023/08/24 00:06:52.509] 	at jepsen.checker$compose$reify__10709$fn__10711.invoke(checker.clj:102)
> [2023/08/24 00:06:52.509] 	at clojure.core$pmap$fn__8552$fn__8553.invoke(core.clj:7089)
> [2023/08/24 00:06:52.509] 	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
> [2023/08/24 00:06:52.509] 	at clojure.lang.AFn.call(AFn.java:18)
> [2023/08/24 00:06:52.509] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> [2023/08/24 00:06:52.509] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> [2023/08/24 00:06:52.509] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> [2023/08/24 00:06:52.509] 	at java.base/java.lang.Thread.run(Thread.java:829)
> [2023/08/24 00:06:54.572] INFO [2023-08-24 00:06:54,572] jepsen test runner - jepsen.core Analysis complete

**Comment by aphyr** [comment]
This is a work-in-progress commit--I haven't finished porting it to the latest version of Jepsen yet. Perhaps you'd like to try 0.3.1?

**Comment by juangugit** [comment]
Thanks for your quick reply.
I switched to 0.3.1, I got an new error message: Could you please take a look? Thanks
```
[2023/08/24 05:53:38.897] INFO [2023-08-24 05:53:36,909] jepsen test runner - jepsen.core Analyzing...
[2023/08/24 05:53:38.897] INFO [2023-08-24 05:53:38,897] clojure-agent-send-off-pool-14 - elle.txn Timing out search for :G-nonadjacent in SCC of 125 transactions (checked [:G0 :G1c :G-single :G-nonadjacent] )
[2023/08/24 05:53:40.691] INFO [2023-08-24 05:53:40,691] clojure-agent-send-off-pool-14 - elle.txn Timing out search for :G-single in SCC of 222 transactions (checked [:G0 :G1c :G-single] )
[2023/08/24 05:53:40.771] INFO [2023-08-24 05:53:40,770] clojure-agent-send-off-pool-25 - elle.viz Skipping plot of 78177 bytes
[2023/08/24 05:53:41.458] INFO [2023-08-24 05:53:41,457] clojure-agent-send-off-pool-61 - elle.viz Skipping plot of 147424 bytes
[2023/08/24 05:53:41.486] INFO [2023-08-24 05:53:41,486] jepsen test runner - jepsen.core Analysis complete
```

**Comment by aphyr** [comment]
This is fine. Mongo allows anomalies that form large transaction cycles; Elle's just letting you know it can't complete an exhaustive search of those cycles in a reasonable time.
