### ISSUE TITLE
False positive on lost update

### ISSUE THREAD

**Issue by bsbds** [jepsen-io/elle#28]
Hi, I recently use jepsen to test our database, and I suspect that elle sometimes generates false-positive lost update anomalies during history analyses.

To reproduce, consider the following jepsen history:
```clojure
(def h (h/history
        [{:index 0 :time 0 :type :invoke :process 0 :f :txn :value [[:r 1 nil] [:w 1 2]]}
         {:index 1 :time 1 :type :invoke :process 1 :f :txn :value [[:r 1 nil] [:w 1 3]]}
         {:index 2 :time 2 :type :ok :process 0 :f :txn :value [[:r 1 2] [:w 1 2]]}
         {:index 3 :time 3 :type :ok :process 1 :f :txn :value [[:r 1 2] [:w 1 3]]}]))
```

1. The first txn writes the exact same value as the initial value.
2. The second txn writes a different value to the key.

It appears that elle would interpret the second txn as having read the initial value and thereby generating a false-positive lost update anomaly.

**Comment by nurturenature** [comment]
> The first txn writes the exact same value as the initial value.

That's not a possible scenario.

All initial values are nil, and every write is unique.

Guessing you using something other than Jepsen to generate the test histories?

**Comment by aphyr** [comment]
Can I ask how you got this history? Elle initial values are always supposed to be `nil`, not `2`. If you're getting a `2` out of thin air, something is seriously wrong with this database and Elle *should* be complaining about it.

**Comment by bsbds** [comment]
> Can I ask how you got this history? Elle initial values are always supposed to be `nil`, not `2`. If you're getting a `2` out of thin air, something is seriously wrong with this database and Elle _should_ be complaining about it.

Sorry, I realize I made a mistake. I assumed the key had an initial value, but the same value shouldn't be written by more than one operation. Thanks for the clarification!
