### ISSUE TITLE
Feature: add delete operation 

### ISSUE THREAD

**Issue by qvad** [jepsen-io/elle#9]
Currently elle supports reads and writes/appends. Is there a way to add delete operations?

**Comment by aphyr** [comment]
Wow, so github... just never emailed me about *any* of this, huh? Yes, you could imagine a way to do deletions, but a.) I think that ruins the rest of Elle's analysis, and b.) you can only do it once. I think this is probably best addressed via a separate Elle workload.

**Comment by qvad** [comment]
Sorry, it's probably a very popular question :)
Got it, thanks

I mean there is a lot of tricky logic around removes in DB, and usually it has issues inside. There is probably a way to revert logic, something like writes will be deletes... maybe it's stupid, but I'll try)
